[workspace]
members = [
    "opentelemetry",
    "opentelemetry-api",
    "opentelemetry-aws",
    "opentelemetry-contrib",
    "opentelemetry-datadog",
    "opentelemetry-dynatrace",
    "opentelemetry-http",
    "opentelemetry-jaeger",
    "opentelemetry-otlp",
    "opentelemetry-prometheus",
    "opentelemetry-proto",
    "opentelemetry-sdk",
    "opentelemetry-semantic-conventions",
    "opentelemetry-stackdriver",
    "opentelemetry-zipkin",
    "opentelemetry-zpages",
    "examples/actix-http",
    "examples/actix-http-tracing",
    "examples/actix-hyper",
    "examples/actix-udp",
    "examples/async",
    "examples/aws-xray",
    "examples/basic-otlp",
    "examples/basic-otlp-http",
    "examples/datadog",
    "examples/dynatrace",
    "examples/external-otlp-tonic-tokio",
    "examples/grpc",
    "examples/http",
    "examples/hyper-prometheus",
    "examples/traceresponse",
    "examples/tracing-grpc",
    "examples/jaeger-remote-sampler",
    "examples/zipkin",
    "examples/multiple-span-processors",
    "examples/zpages",
    "examples/wasm-wasi-bring-your-own-client"
]
exclude = ["examples/external-otlp-grpcio-async-std"]

[patch.crates-io]
opentelemetry = { path = "./opentelemetry"}
opentelemetry-otlp = { path = "./opentelemetry-otlp"}
opentelemetry-http = { path = "./opentelemetry-http"}
opentelemetry_api = { path = "./opentelemetry-api"}
